version: '3.8'

services:
  web:
    restart: always
    command: python manage.py run --host 0.0.0.0
    build: project/
    volumes:
      - ./project/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aggregator_db