version: '3.8'

services:
  web:
    command: python manage.py run --host 0.0.0.0
    build: project/
    ports:
      - 80:5000
    env_file:
      - .env.dev
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aggregator_db